development:
  sessions:
    default:
      database: monrails_development
      hosts:
        - localhost:27017
      options:
  options:
    raise_not_found_error: false
test:
  sessions:
    default:
      database: monrails_test
      hosts:
        - localhost:27017
      options:
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
  options:
    raise_not_found_error: false

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
  options:
    raise_not_found_error: false
